# Generated by Django 5.2 on 2025-05-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.AlterModelTable(
            name='paymentstatus',
            table='payment_status',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
        migrations.AlterModelTable(
            name='shoppingcart',
            table='shopping_cart',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
